### ISSUE TITLE
Call to undefined method TeamPickr\DistanceMatrix\DistanceMatrix::response()

### ISSUE THREAD

**Issue by Rahvayana** [teampickr/php-google-maps-distance-matrix#5]
why response method isn't exist in DistanceMatrix.php?

**Comment by juliomotol** [comment]
Having the same problem

Edit:

I found the correct method for this and its `DistanceMatrix::request()`. Please update the documentation.

**Comment by Jono20201** [comment]
I believe this is now up to date.
